### ISSUE TITLE
Color control in the theme customizer 

### ISSUE THREAD

**Issue by Sergio-Rojas-Blanco** [kallookoo/wp-color-picker-alpha-plugin#1]
Hi there, [@kallookoo](https://github.com/kallookoo) thanks for your work.
I'm creating sections in the customizer of my theme (undestrap-child) to control the background color and opacity of the main menu and the widgets.

I've installed wp-color-picker-alpha-plugin but the alpha control doesn't appear. I'm using wp 4.9.4.

I tried to follow the indications of wp-color-picker-alpha but I'm quite clumsy. 

I tried with a twentysenventeen child theme. I've created a folder js. I have copied wp-color-picker-alpha.min.js into it. I've enqueued it in my functions.php:
```
/ ** WP Color Picker Alpha ** /
wp_enqueue_style ('wp-color-picker');
wp_enqueue_script ('wp-color-picker-alpha', get_stylesheet_directory_uri (). '/js/wp-color-picker-alpha.min.js', array ('wp-color-picker'), $ current_version, $ in_footer) ;
```
I have modified header.php and heade-image.php to point to my site-branding.php. I have modified the div of the header text:

`<div class = "site-branding color-picker" data-alpha = "true">`

but the alpha control doesn't appear. I attach an **[capture](https://github.com/Nanosergio/files/blob/master/wp-color-picker-alpha.jpg?raw=true)**. What am I doing wrong?

Excuse my ignorance. All help is welcome.

**Comment by kallookoo** [comment]
No, no! This plugin is only for view all options not by using with your customizer, you have to the script with custom customize class, see wp-color-picker-alpha repository and search (google) how to do it.

**Comment by Nanosergio** [comment]
Thanks kallookoo, I've already tried.
Please see my last comment:

"I tried to follow the indications of wp-color-picker-alpha but I'm quite clumsy.

I tried with a twentysenventeen child theme. I've created a folder js. I have copied wp-color-picker-alpha.min.js into it. I've enqueued

 it in my functions.php:

/ ** WP Color Picker Alpha ** /
wp_enqueue_style ('wp-color-picker');
wp_enqueue_script ('wp-color-picker-alpha', get_stylesheet_directory_uri (). '/js/wp-color-picker-alpha.min.js', array ('wp-color-picker'), $ current_version, $ in_footer) ;
I have modified header.php and heade-image.php to point to my site-branding.php. I have modified the div of the header text:

<div class = "site-branding color-picker" data-alpha = "true">

but the alpha control doesn't appear. I attach an capture. What am I doing wrong?"

**Comment by kallookoo** [comment]
See [http://braadmartin.com/alpha-color-picker-control-for-the-wordpress-customizer/](http://braadmartin.com/alpha-color-picker-control-for-the-wordpress-customizer/) by example.
But by default header already exists in WordPress core and not is possible overwritte (that I remember now) is neccesary to create new customize by change the header text and disabled of the core opcion or publish your question in wordpress forum, sorry by not is one problem for this script or you pass me the code by private and I do it to you but you would need to pay me.

Me puedes hablar en castellano, soy de españa.

**Comment by Sergio-Rojas-Blanco** [comment]
Thank you.

Lo sé. He visto que eres de Barcelona. Era por el resto usuarios. También he visto tu cuenta de twitter e Instagram, una selección muy chula.

Muchas gracias por tu esfuerzo y atención.

**Comment by kallookoo** [comment]
Tienes razon, no lo habia pensado.
Espero que puedas conseguirlo, pero si miras el codex y el enlace que puse, y sabes algo de programacion, estoy seguro que lo conseguiras.
