### ISSUE TITLE
Changes aren't triggered on first selection

### ISSUE THREAD

**Issue by maddisondesigns** [kallookoo/wp-color-picker-alpha-plugin#3]
I've installed this plugin to look at the changes that you've made with this new version (thanks for all your work on this).

After selecting the control in the Customizer, the first colour selection doesn't trigger a change in the control which means the Publish button doesn't become active. The Publish button only becomes active once you've selected a different colour the second time.

Here's a vid to show what's happening:  https://share.getcloudapp.com/X6udj4oW

**Comment by kallookoo** [comment]
When testing it, use a slider.
Now I have used a color from the palette and it is true that it does not detect the change as you say.
It is already solved, the problem was in the change of the wpColorPicker and how it checked if the color was different.
Thanks for your notice.
